name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Restore keystore
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" -d > smartautoclicker.jks.asc
        gpg --batch --yes --decrypt --passphrase ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }} --output smartautoclicker/smartautoclicker.jks smartautoclicker.jks.asc
    - name: Build with Gradle
      run: |
        ./gradlew \
          -PsigningStorePassword="${{ secrets.SIGNING_STORE_PASSWORD }}" \
          -PsigningKeyAlias="${{ secrets.SIGNING_KEY_ALIAS }}" \
          -PsigningKeyPassword="${{ secrets.SIGNING_KEY_PASSWORD }}" \
          assembleFDroidRelease bundleFDroidRelease
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: smartautoclicker-release
        path: smartautoclicker/build/outputs/
